In [1]:
import numpy as np
import pandas as pd
date = pd.read_csv('/kaggle/input/datasets/goutampatel18/orders-and-messages/orders.csv')
time = pd.read_csv('/kaggle/input/datasets/goutampatel18/orders-and-messages/messages.csv')
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [2]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [3]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [4]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

# Working with Dates

In [5]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [6]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

# 1. Extract year

In [7]:
date['date_year'] = date['date'].dt.year

date.sample(5)

          date  product_id  city_id  orders  date_year
361 2018-10-13         124       26       2       2018
674 2018-08-31        4867        9       5       2018
742 2018-07-15        3627       13      21       2018
829 2019-09-18         287        6       4       2019
478 2018-12-22         711       30       3       2018

# Extract Month

In [8]:
date['date_month_no'] = date['date'].dt.month

date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

# Extract Days

In [9]:

date['date_day'] = date['date'].dt.day

date.head()

        date  product_id  city_id  orders  date_year  date_month_no  date_day
0 2019-12-10        5628       25       3       2019             12        10
1 2018-08-15        3646       14     157       2018              8        15
2 2018-10-23        1859       25       1       2018             10        23
3 2019-08-17        7292       25       1       2019              8        17
4 2019-01-06        4344       25       3       2019              1         6

In [10]:
# day of week
date['date_dow'] = date['date'].dt.dayofweek

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_day,date_dow
0,2019-12-10,5628,25,3,2019,12,10,1
1,2018-08-15,3646,14,157,2018,8,15,2
2,2018-10-23,1859,25,1,2018,10,23,1
3,2019-08-17,7292,25,1,2019,8,17,5
4,2019-01-06,4344,25,3,2019,1,6,6

In [11]:
# day of week - name

date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

        date  date_year  date_month_no  date_day  date_dow date_dow_name
0 2019-12-10       2019             12        10         1       Tuesday
1 2018-08-15       2018              8        15         2     Wednesday
2 2018-10-23       2018             10        23         1       Tuesday
3 2019-08-17       2019              8        17         5      Saturday
4 2019-01-06       2019              1         6         6        Sunday

In [12]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,10,1,Tuesday,0
1,2018-08-15,2018,8,15,2,Wednesday,0
2,2018-10-23,2018,10,23,1,Tuesday,0
3,2019-08-17,2019,8,17,5,Saturday,1
4,2019-01-06,2019,1,6,6,Sunday,1

# Extract Quarter

In [13]:

date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend,quarter
0,2019-12-10,2019,12,10,1,Tuesday,0,4
1,2018-08-15,2018,8,15,2,Wednesday,0,3
2,2018-10-23,2018,10,23,1,Tuesday,0,4
3,2019-08-17,2019,8,17,5,Saturday,1,3
4,2019-01-06,2019,1,6,6,Sunday,1,1

# Extract Semester

In [14]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend,quarter,semester
0,2019-12-10,2019,12,10,1,Tuesday,0,4,2
1,2018-08-15,2018,8,15,2,Wednesday,0,3,2
2,2018-10-23,2018,10,23,1,Tuesday,0,4,2
3,2019-08-17,2019,8,17,5,Saturday,1,3,2
4,2019-01-06,2019,1,6,6,Sunday,1,1,1

# Extract Time elapsed between dates

In [15]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 4, 21, 8, 39, 20, 812143)

In [16]:
today - date['date']

0     2324 days 08:39:20.812143
1     2806 days 08:39:20.812143
2     2737 days 08:39:20.812143
3     2439 days 08:39:20.812143
4     2662 days 08:39:20.812143
                 ...
995   2752 days 08:39:20.812143
996   2693 days 08:39:20.812143
997   2541 days 08:39:20.812143
998   2606 days 08:39:20.812143
999   2380 days 08:39:20.812143
Name: date, Length: 1000, dtype: timedelta64[ns]

In [17]:
(today - date['date']).dt.days

0      2324
1      2806
2      2737
3      2439
4      2662
       ...
995    2752
996    2693
997    2541
998    2606
999    2380
Name: date, Length: 1000, dtype: int64

In [18]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [19]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

# Extract Time part

In [20]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

# Time difference

In [21]:
today - time['date']

0     4510 days 07:49:20.812143
1     4374 days 08:59:20.812143
2     4860 days 08:18:20.812143
3     4162 days 08:08:20.812143
4     4559 days 09:28:20.812143
                 ...
995   5149 days 07:49:20.812143
996   4470 days 09:25:20.812143
997   4935 days 09:02:20.812143
998   5051 days 09:05:20.812143
999   4323 days 09:14:20.812143
Name: date, Length: 1000, dtype: timedelta64[ns]

In [22]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.896922e+08
1      3.779460e+08
2      4.199339e+08
3      3.596261e+08
4      3.939317e+08
           ...
995    4.449018e+08
996    3.862419e+08
997    4.264165e+08
998    4.364391e+08
999    3.735405e+08
Name: date, Length: 1000, dtype: float64

In [23]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.494869e+06
1      6.299099e+06
2      6.998898e+06
3      5.993768e+06
4      6.565528e+06
           ...
995    7.415029e+06
996    6.437365e+06
997    7.106942e+06
998    7.273985e+06
999    6.225674e+06
Name: date, Length: 1000, dtype: float64

In [24]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      108247.822448
1      104984.989114
2      116648.305781
3       99896.139114
4      109425.472448
           ...
995    123583.822448
996    107289.422448
997    118449.039114
998    121233.089114
999    103761.239114
Name: date, Length: 1000, dtype: float64